# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestDowloadFile' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod "MZDownloadManager"


  # Pods for TestDowloadFile

  target 'TestDowloadFileTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestDowloadFileUITests' do
    # Pods for testing
  end

end
